version: "3"

services:
  db:
    image: postgres
    container_name: db
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data

  app:
    build: .
    tty: true
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env

